app:
  image: ibmcom/swift-ubuntu:3.1.1
  ports:
    - "8080:8080"
  volumes:
    - .:/BlueRSA
  command: bash -c "cd /BlueRSA && swift package  --build-path .build-ubuntu clean && swift build  --build-path .build-ubuntu && swift test  --build-path .build-ubuntu"
